package view;

import controller.ProductController;
import controller.TransactionController;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Product;
import model.PurchaseItemDto;


public class CashierView extends javax.swing.JFrame {
    private final ProductController productController = new ProductController();
    private boolean  isAddAction  = true; // fasle for update
    private final TransactionController transactionController = new TransactionController();
    
    Product selectedProduct = null;
    List<Product> products;
    List<PurchaseItemDto> purchaseItemDtos = new ArrayList<>();
    public CashierView() {
        initComponents();
        setComponent(false);
        reloadTables();
    }
    
    
    public void setComponent(boolean value){
          inputQuantity.setEnabled(value);
          buttonAddChart.setEnabled(value);
          buttonClearChart.setEnabled(false);
          buttonConfirm.setEnabled(false);
    }
    

    public void clearText(){
           inputQuantity.setText("");
    }
    
    
    public TableProductView mapToTableProduct(String query){
        products = productController.read(query);
        products =  products.stream().filter(p -> p.getStock() > 0).collect(Collectors.toList());
        return new  TableProductView(products);
    }
    
    public ShoppingChartView mapToShoppingChart(){
        return  new ShoppingChartView(purchaseItemDtos);
    }
    public void reloadTables(){
        productTable.setModel(mapToTableProduct(""));
        tableChart.setModel(mapToShoppingChart());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        buttonCashier = new javax.swing.JButton();
        buttonCashier1 = new javax.swing.JButton();
        tableScrollPanel = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        inputQuantity = new javax.swing.JTextField();
        buttonAddChart = new javax.swing.JButton();
        labelNamaProduk = new javax.swing.JLabel();
        scrollPanelChart = new javax.swing.JScrollPane();
        tableChart = new javax.swing.JTable();
        buttonConfirm = new javax.swing.JButton();
        buttonClearChart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1000, 800));

        header.setBackground(new java.awt.Color(241, 183, 119));

        headerLabel.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(0, 0, 0));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("WARKOP PBO");

        buttonCashier.setText("Stock");
        buttonCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCashierMouseClicked(evt);
            }
        });
        buttonCashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCashierActionPerformed(evt);
            }
        });

        buttonCashier1.setText("Report");
        buttonCashier1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCashier1MouseClicked(evt);
            }
        });
        buttonCashier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCashier1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCashier1)
                .addGap(29, 29, 29)
                .addComponent(buttonCashier)
                .addGap(83, 83, 83))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(headerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCashier)
                    .addComponent(buttonCashier1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        tableScrollPanel.setViewportView(productTable);

        buttonAddChart.setText("Tambah Ke Keranjang");
        buttonAddChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddChartActionPerformed(evt);
            }
        });

        labelNamaProduk.setForeground(new java.awt.Color(0, 0, 0));
        labelNamaProduk.setText("Nama Produk   X ");

        tableChart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableChart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableChartMouseClicked(evt);
            }
        });
        scrollPanelChart.setViewportView(tableChart);

        buttonConfirm.setText("Konfirmasi Transaksi");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });

        buttonClearChart.setText("Kosongkan Keranjang");
        buttonClearChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearChartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(labelNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddChart))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(scrollPanelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonConfirm)
                            .addComponent(buttonClearChart))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddChart)
                    .addComponent(labelNamaProduk))
                .addGap(28, 28, 28)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(buttonConfirm)
                        .addGap(18, 18, 18)
                        .addComponent(buttonClearChart))
                    .addComponent(scrollPanelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, 805, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        inputQuantity.setText("");
        setComponent(true);
        int clickedRow = productTable.getSelectedRow(); 
        TableModel tableModel =  productTable.getModel();
       selectedProduct = products.get(clickedRow);
       labelNamaProduk.setText(selectedProduct.getName()  + "   X ");
    }//GEN-LAST:event_productTableMouseClicked

    private void buttonCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCashierMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCashierMouseClicked

    private void buttonCashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCashierActionPerformed
        ProductView pv = new ProductView();
        this.dispose();
        pv.setVisible(true);
    }//GEN-LAST:event_buttonCashierActionPerformed

    private void buttonAddChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddChartActionPerformed
        buttonConfirm.setEnabled(true);
        buttonClearChart.setEnabled(true);
        PurchaseItemDto purchaseItemDto = new PurchaseItemDto(selectedProduct, Integer.valueOf( inputQuantity.getText()));
        purchaseItemDtos.add(purchaseItemDto);
        reloadTables();
    }//GEN-LAST:event_buttonAddChartActionPerformed

    private void tableChartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableChartMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableChartMouseClicked

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed
        String total = transactionController.doProductPurchaseTransaction(purchaseItemDtos);
        purchaseItemDtos.clear();
        reloadTables();
        JOptionPane.showMessageDialog(null, "Transaksi Berhasil, Total Transaksi : " + total, "Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void buttonClearChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearChartActionPerformed
        buttonConfirm.setEnabled(false);
        buttonClearChart.setEnabled(false);
        purchaseItemDtos.clear();
       reloadTables();
    }//GEN-LAST:event_buttonClearChartActionPerformed

    private void buttonCashier1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCashier1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCashier1MouseClicked

    private void buttonCashier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCashier1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCashier1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton buttonAddChart;
    private javax.swing.JButton buttonCashier;
    private javax.swing.JButton buttonCashier1;
    private javax.swing.JButton buttonClearChart;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.JPanel header;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JTextField inputQuantity;
    private javax.swing.JLabel labelNamaProduk;
    private javax.swing.JTable productTable;
    private javax.swing.JScrollPane scrollPanelChart;
    private javax.swing.JTable tableChart;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
